### ISSUE TITLE
Schedule Tests to Run Periodically

### ISSUE THREAD

**Issue by jasonrogena** [onaio/ansible-postgresql#13]
To prevent us from ending up in situations where we realize this role is broken when it's run against a deployment, schedule the tests to run periodically (I think GitHub Actions supports this already, not too sure about Travis CI).

Role is a bit fragile in this sense because of its reliance on other roles (ANXS.postgresql, onaio.gpg-import, and onaio.backup) being compatible with each other's changes.

**Comment by evansmurithi** [comment]
Some docs:
- https://www.jeffgeerling.com/blog/2020/running-github-actions-workflow-on-schedule-and-other-events
- https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule
